[pytest]
markers =
    gui: marks tests as GUI tests (select with '-m gui')
    slow: marks tests as slow (deselect with '-m "not slow"')

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = 
    --strict-markers
    --strict-config
    -v
    --capture=no
    --browser firefox
    
# Async settings
asyncio_mode = strict